// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    attributes: {
      name: {
        type: 'string',
        required: true
      },
      email: {
        type: 'email',
        required: true,
        unique: true
      },
      password: {
        type: 'string',
        required: true
      },
      zipcode: {
        type: 'string',
        maxLength: 6,
        minLength: 4
      },
      lists: {
        type: 'array'
      }
    }
  };

}).call(this);
